### ISSUE TITLE
print_field bug

### ISSUE THREAD

**Issue by chasebroder** [yth/CS4500A1P1#1]
Hi,

While adapting your sorer to use in our Project 1, my partner and I uncovered a bug in your print_field method. Line 345 of helper.h should read "if (new_start <= new_end) {". Currently, without the equals, all single-digit values (all booleans and single-digit ints) will end up failing that if statement, and outputting a 1. 

Hope this helps!

**Comment by Danijj89** [comment]
Thanks for the comment. We just finished adapting our sorer today and I was encountered the same issue and fixed it on my new repository but did not update this one. (We weren't expecting anybody to use ours).
In the case you happen to find more issues please let us know. We can definitely help working through them if needed.
